# Escolha uma imagem base do Node.js
FROM node:16

# Defina o diretório de trabalho
WORKDIR /app

# Copie o arquivo package.json e package-lock.json
COPY package.json ./

# Instale as dependências
RUN npm install

# Copie todo o código da aplicação para dentro do container
COPY . .

# Exponha a porta que o app vai rodar
EXPOSE 80

# Comando para rodar a aplicação
CMD ["npm", "start"]
